# 0 - Inicialização

In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

from plotly import graph_objects as go
import plotly as py

from datetime import datetime
from datetime import timedelta

import xgboost
from sklearn.model_selection import train_test_split
from sklearn.metrics import plot_confusion_matrix, accuracy_score, f1_score, confusion_matrix, recall_score, precision_score

from sklearn.utils import resample

# 1 - Classificar o dataset clusterizado por dia

## Carregar dados

In [2]:
df_cluster = pd.read_csv('../../../data/cleandata/Info pluviometricas/Merged Data/clustered_label.csv', sep = ';')
df_cluster['Data_Hora'] = pd.to_datetime(df_cluster['Data_Hora'], yearfirst=True)
df_cluster['Data'] = df_cluster['Data_Hora'].dt.strftime('%Y-%m-%d')
df_cluster

Data_Hora        Local  UmidadeRelativa  PressaoAtmosferica  \
0       2011-01-01 00:00:00       Erasmo             88.8               920.5   
1       2011-01-01 00:00:00  Camilopolis             84.8               920.6   
2       2011-01-01 00:00:00      Paraiso             92.3               919.1   
3       2011-01-01 00:00:00      Vitoria              0.0                 0.0   
4       2011-01-01 00:00:00           RM             86.6               926.7   
...                     ...          ...              ...                 ...   
1463565 2019-06-30 23:45:00  Camilopolis             54.4               924.0   
1463566 2019-06-30 23:45:00           RM             66.9               931.9   
1463567 2019-06-30 23:45:00      Vitoria             38.4               925.8   
1463568 2019-06-30 23:45:00      Paraiso             55.3               924.2   
1463569 2019-06-30 23:45:00       Erasmo             60.7               925.7   

         TemperaturaDoAr  TemperaturaInterna  PontoDeOrvalho  RadiacaoSolar  \
0              10.243265                22.9       17.700000       0.000000   
1              20.200000                22.8       17.500000       0.000000   
2              19.300000                22.7       18.000000       0.000000   
3               0.000000                 0.0        0.000000       0.000000   
4              20.100000                23.3       17.800000       0.000000   
...                  ...                 ...             ...            ...   
1463565        20.800000                23.0       12.200000       0.073893   
1463566        18.800000                22.5       13.300000       0.294461   
1463567        20.300000                27.5        6.300000       0.000000   
1463568        20.800000                22.1       11.790525       0.000000   
1463569        19.500000                22.5       11.700000       0.000000   

         DirecaoDoVento  VelocidadeDoVento  Precipitacao  LocalMax_Dia  \
0                 133.0                0.7           0.0             0   
1                 137.0                1.5           0.0             0   
2                 101.0                2.6           0.0             0   
3                   0.0                0.0           0.0             0   
4                 131.0                2.5           0.0             0   
...                 ...                ...           ...           ...   
1463565           332.0                4.3           0.0             0   
1463566           331.0                0.7           0.0             0   
1463567             0.0                0.0           0.0             0   
1463568            25.0                3.6           0.0             0   
1463569           327.0                3.5           0.0             0   

         LocalMax_Hora        Data  
0                    0  2011-01-01  
1                    0  2011-01-01  
2                    0  2011-01-01  
3                    0  2011-01-01  
4                    0  2011-01-01  
...                ...         ...  
1463565              0  2019-06-30  
1463566              0  2019-06-30  
1463567              0  2019-06-30  
1463568              0  2019-06-30  
1463569              0  2019-06-30  

[1463570 rows x 14 columns]

## Agrupar por dia

In [12]:
# df_cluster_dia = df_cluster.drop(columns = ['Data_Hora', 'LocalMax_Hora']).rename(columns = {'LocalMax_Dia': 'LocalMax'})
# s_prec_p = df_cluster_dia.groupby(['Data', 'Local']).sum().reset_index().groupby('Data').mean()['Precipitacao'].reset_index()
# s_prec_o = df_cluster_dia.groupby(['Data', 'Local']).max().reset_index().groupby('Data').max()['LocalMax'].reset_index()
# df_cluster_dia = df_cluster_dia.groupby(['Data']).mean().reset_index()
# df_cluster_dia['Precipitacao'] = s_prec_p['Precipitacao']
# df_cluster_dia['LocalMax'] = s_prec_o['LocalMax']
# df_cluster_dia

df_cluster_dia = df_cluster.drop(columns = ['Data_Hora', 'LocalMax_Hora']).rename(columns = {'LocalMax_Dia': 'LocalMax'})
df_prec_p = df_cluster_dia.groupby(['Data', 'Local']).sum()['Precipitacao'].reset_index()
df_prec_o = df_cluster_dia.groupby(['Data', 'Local']).max()['LocalMax'].reset_index()
df_cluster_dia = df_cluster_dia.groupby(['Data', 'Local']).mean().reset_index().drop(columns = ['Precipitacao', 'LocalMax'])
df_cluster_dia = df_cluster_dia.merge(df_prec_p, on = ['Data', 'Local'])
df_cluster_dia = df_cluster_dia.merge(df_prec_o, on = ['Data', 'Local'])
df_cluster_dia['Local'] = df_cluster_dia['Local'].replace({'Camilopolis': 1, 'Erasmo': 2, 'Paraiso': 3, 'RM': 4, 'Vitoria': 5})
df_cluster_dia['Mes'] = df_cluster_dia['Data'].str[5:7].astype(int)
df_cluster_dia

Data  Local  UmidadeRelativa  PressaoAtmosferica  \
0      2011-01-01      1        80.037996          918.279493   
1      2011-01-01      2        82.882941          918.304598   
2      2011-01-01      3        83.588051          916.817234   
3      2011-01-01      4        81.887094          924.393186   
4      2011-01-01      5         0.000000            0.000000   
...           ...    ...              ...                 ...   
15345  2019-06-30      1        50.984375          924.260417   
15346  2019-06-30      2        52.906250          925.870833   
15347  2019-06-30      3        52.266667          924.503125   
15348  2019-06-30      4        54.458333          932.079167   
15349  2019-06-30      5        33.409375          925.964583   

       TemperaturaDoAr  TemperaturaInterna  PontoDeOrvalho  RadiacaoSolar  \
0            20.981523           24.507206       17.288055     132.072917   
1            20.023345           24.302490       17.296642     134.354167   
2            20.256149           24.174391       17.407144     160.770833   
3            20.809716           24.522501       17.479821     154.968750   
4             0.000000            0.000000        0.000000       0.000000   
...                ...                 ...             ...            ...   
15345        21.940625           24.225000       12.049696     146.491123   
15346        21.695833           24.270707       11.334375       0.000000   
15347        22.107292           23.691667       11.917331     142.864583   
15348        21.626042           25.279167       12.515625     169.933156   
15349        22.151042           28.868750        5.421875       0.000000   

       DirecaoDoVento  VelocidadeDoVento  Precipitacao  LocalMax  Mes  
0          143.062500           2.160417           0.6         0    1  
1          124.833333           2.959375           2.2         0    1  
2          146.114583           2.661458           1.6         0    1  
3          158.187500           2.942708           3.2         0    1  
4            0.000000           0.000000           0.0         0    1  
...               ...                ...           ...       ...  ...  
15345      301.906250          13.586458           0.0         0    6  
15346      237.510417           8.039442           0.0         0    6  
15347      144.958333           9.913450           0.0         0    6  
15348      263.375000           6.782296           0.0         0    6  
15349        0.000000           0.000000           0.0         0    6  

[15350 rows x 13 columns]

In [13]:
xgb = xgboost.XGBClassifier()

cols_rem = ['LocalMax', 'Data']

x = df_cluster_dia[[c for c in df_cluster_dia.columns if c not in cols_rem]]
y = df_cluster_dia['LocalMax']

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state = 378)

# concatenate our training data back together
X = pd.concat([x_treino, y_treino], axis=1)

# separate minority and majority classes
not_ordem = X[X['LocalMax']==0].copy()
ordem = X[X['LocalMax']==1].copy()

# upsample minority
ordem_upsampled = resample(ordem,
                        replace=True, # sample with replacement
                        n_samples=len(not_ordem), # match number in majority class
                        random_state=378) # reproducible results

# combine majority and upsampled minority
upsampled = pd.concat([not_ordem, ordem_upsampled])

x_treino = upsampled[[c for c in df_cluster_dia.columns if c not in cols_rem]]
y_treino = upsampled['LocalMax']

display(y_treino.value_counts())

#xgb.fit(x_treino, y_treino, eval_set = [(x_treino, y_treino), (x_teste, y_teste)], eval_metric=f1_score)
param = {'max_depth':10, 'eta':2, 'objective':'binary:logistic', 'min_child_weight': 1, 'lambda': 1, 'alpha': 0, 'gamma': 0}

df_train = xgboost.DMatrix(data=x_treino, label=y_treino)

bst = xgboost.train(param, df_train, 2, feval=f1_score)
y_teste_pred = bst.predict(xgboost.DMatrix(data=x_teste, label=y_teste))
y_teste_pred = [1 if i>0.5 else 0 for i in y_teste_pred]
y_treino_pred = bst.predict(xgboost.DMatrix(data=x_treino, label=y_treino))
y_treino_pred = [1 if i>0.5 else 0 for i in y_treino_pred]

print(f"Treino: {accuracy_score(y_treino, y_treino_pred)}")
print(f"Teste: {accuracy_score(y_teste, y_teste_pred)}")
print(f"Precisão: {precision_score(y_teste, y_teste_pred)}")
print(f"Recall: {recall_score(y_teste, y_teste_pred)}")
print(f"F1: {f1_score(y_teste, y_teste_pred)}")
display(confusion_matrix(y_teste, y_teste_pred, normalize='true'))
display(confusion_matrix(y_teste, y_teste_pred,))

1    10448
0    10448
Name: LocalMax, dtype: int64

Treino: 0.9100784839203675
Teste: 0.9155266015200869
Precisão: 0.0804953560371517
Recall: 0.22033898305084745
F1: 0.11791383219954647


array([[0.93380878, 0.06619122],
       [0.77966102, 0.22033898]])

array([[4190,  297],
       [  92,   26]], dtype=int64)

# 2 - Classificar o dataset clusterizado por 15 mins

In [104]:
df_label_d = pd.read_csv('../../../data/cleandata/Ordens de serviço/labels_day.csv', sep = ';')
df_cluster_hora = df_cluster.merge(df_label_d[['Data', 'LocalMax']], on = 'Data', how = 'left').fillna(0)
df_cluster_hora = df_cluster_hora.drop(columns=['LocalMax_Hora', 'LocalMax_Dia'])

In [105]:
#df_cluster_hora = df_cluster.copy()
#df_cluster_hora = df_cluster_hora.drop(columns=['LocalMax_Hora']).rename(columns = {'LocalMax_Dia': 'LocalMax'})
df_cluster_hora = df_cluster_hora.sort_values(by=['Data_Hora', 'Local'])

In [106]:
df_cluster_hora.groupby('LocalMax').count()

Data_Hora    Local  UmidadeRelativa  PressaoAtmosferica  \
LocalMax                                                            
0.0         1418705  1418705          1418705             1418705   
1.0           44865    44865            44865               44865   

          TemperaturaDoAr  TemperaturaInterna  PontoDeOrvalho  RadiacaoSolar  \
LocalMax                                                                       
0.0               1418705             1418705         1418705        1418705   
1.0                 44865               44865           44865          44865   

          DirecaoDoVento  VelocidadeDoVento  Precipitacao     Data  
LocalMax                                                            
0.0              1418705            1418705       1418705  1418705  
1.0                44865              44865         44865    44865

Prec24h -> soma da precipitação nas últimas 24 horas

In [107]:
# for i in range(24*4):
#     df_cluster_hora['Prec_Shift_' + str(i)] = df_cluster_hora['Precipitacao'].shift(-5 * (i+1), fill_value=0)

# df_cluster_hora['Prec24h'] = df_cluster_hora[[c for c in df_cluster_hora.columns if 'Prec_Shift' in c]].sum(axis=1)
# df_cluster_hora = df_cluster_hora.drop(columns = [c for c in df_cluster_hora.columns if 'Prec_Shift' in c])
# df_cluster_hora.head(10)

PrecMomento -> soma da precipitação até aquele momento do dia

In [127]:
init_time = datetime.now()
def getPrecMomento(x):
    return df_cluster_hora.loc[
        (df_cluster_hora['Data'] == x['Data']) &
        (df_cluster_hora['Data_Hora'] <= x['Data_Hora']) &
        (df_cluster_hora['Local'] == x['Local']), 'Precipitacao'
    ].sum()

#df_cluster_hora['PrecMomento'] = df_cluster_hora.apply(getPrecMomento, axis=1)
df_cluster_hora.head(100).apply(getPrecMomento, axis=1)
print(datetime.now() - init_time)

0:00:14.958399


In [128]:
df_cluster_hora.shape

(1463570, 13)

PrecSum -> soma da precipitação no dia

In [92]:
df_prec_sum = df_cluster_hora.groupby(['Data', 'Local']).sum().reset_index()[['Data', 'Local', 'Precipitacao']]
df_prec_sum.columns = ['Data', 'Local', 'PrecSum']
df_cluster_hora = df_cluster_hora.merge(df_prec_sum, on=['Data', 'Local'])
df_cluster_hora.head(10)

Data_Hora        Local  UmidadeRelativa  PressaoAtmosferica  \
0 2011-01-01 00:00:00  Camilopolis             84.8               920.6   
1 2011-01-01 00:15:00  Camilopolis             84.1               920.3   
2 2011-01-01 00:30:00  Camilopolis             83.9               920.2   
3 2011-01-01 00:45:00  Camilopolis             83.5               919.9   
4 2011-01-01 01:00:00  Camilopolis             84.0               919.9   
5 2011-01-01 01:15:00  Camilopolis             84.5               919.5   
6 2011-01-01 01:30:00  Camilopolis             84.6               919.4   
7 2011-01-01 01:45:00  Camilopolis             84.5               919.4   
8 2011-01-01 02:00:00  Camilopolis             85.8               919.2   
9 2011-01-01 02:15:00  Camilopolis             86.5               919.0   

   TemperaturaDoAr  TemperaturaInterna  PontoDeOrvalho  RadiacaoSolar  \
0             20.2           22.800000            17.5            0.0   
1             20.1           22.800000            17.4            0.0   
2             20.1           22.900000            17.2            0.0   
3             20.2           22.900000            17.3            0.0   
4             20.1           22.800000            17.3            0.0   
5             20.0           23.143578            17.3            0.0   
6             20.0           23.083792            17.3            0.0   
7             20.0           23.005875            17.3            0.0   
8             19.8           22.935631            17.4            0.0   
9             19.7           22.786449            17.4            0.0   

   DirecaoDoVento  VelocidadeDoVento  Precipitacao        Data  LocalMax  \
0           137.0                1.5           0.0  2011-01-01       0.0   
1            76.0                1.9           0.0  2011-01-01       0.0   
2            92.0                2.9           0.0  2011-01-01       0.0   
3           133.0                1.4           0.0  2011-01-01       0.0   
4           151.0                1.8           0.0  2011-01-01       0.0   
5           124.0                1.8           0.0  2011-01-01       0.0   
6           137.0                1.8           0.0  2011-01-01       0.0   
7           115.0                1.9           0.0  2011-01-01       0.0   
8           155.0                1.8           0.0  2011-01-01       0.0   
9           140.0                1.7           0.0  2011-01-01       0.0   

   Prec24h  PrecSum  
0      0.8      0.6  
1      0.8      0.6  
2      0.8      0.6  
3      0.8      0.6  
4      0.8      0.6  
5      0.8      0.6  
6      0.8      0.6  
7      1.0      0.6  
8      1.2      0.6  
9      1.6      0.6

In [29]:
# df_clustered_total['Hora'] = pd.to_datetime(df_clustered_total['Data_Hora'], yearfirst=True).dt.hour

# df_ohe = df_clustered_total.groupby(['Data', 'Local', 'Hora']).sum().reset_index()[['Data', 'Local', 'Hora', 'Precipitacao']]
# s_ohe = df_ohe['Hora']
# df_ohe = pd.get_dummies(df_ohe, columns = ['Hora'])
# df_ohe['Hora'] = s_ohe

# for i in range(24):
#     df_ohe.loc[df_ohe['Hora_' + str(i)] == 1, 'Hora_' + str(i)] = df_ohe.loc[df_ohe['Hora_' + str(i)] == 1, 'Precipitacao']

# df_clustered_total = df_clustered_total.merge(df_ohe[['Data', 'Local'] + [c for c in df_ohe.columns if 'Hora' in c]], on=['Data', 'Local', 'Hora'])

In [93]:
df_cluster_hora_a = df_cluster_hora.copy()

In [94]:
df_cluster_hora['Hora'] = df_cluster_hora['Data_Hora'].dt.hour
df_cluster_hora['Mes'] = df_cluster_hora['Data_Hora'].dt.month
df_cluster_hora['Local'] = df_cluster_hora['Local'].replace({'Camilopolis': 1, 'Erasmo': 2, 'Paraiso': 3, 'RM': 4, 'Vitoria': 5})


# Filtrando hora no minuto 0
df_hora = df_cluster_hora.groupby(['Data', 'Local', 'Hora']).sum().reset_index()[['Data', 'Local', 'Hora', 'Precipitacao']]
# df_clustered_total = df_clustered_total.groupby(['Data', 'Local', 'Hora']).mean().reset_index()
# s_prec = df_clustered_total.groupby(['Data', 'Local', 'Hora']).sum()[['Precipitacao']]
# df_clustered_total['Precipitacao'] = s_prec

df_cluster_hora['Minuto'] = df_cluster_hora['Data_Hora'].dt.minute
df_cluster_hora = df_cluster_hora[df_cluster_hora['Minuto'] == 0]
#df_cluster_hora = df_cluster_hora.drop(columns = ['Data_Hora', 'Minuto'])
# df_clustered_total = df_clustered_total.drop(columns = ['Data_Hora', 'Minuto', 'Precipitacao'])
# df_clustered_total = df_clustered_total.merge(df_hora, on=['Data', 'Local', 'Hora'])

In [95]:
#df_slice = df_clustered_total[(df_clustered_total['Ordens'] == 1) | (df_clustered_total['Cluster'].isin([1,2]))]
#df_slice = df_clustered_total[(df_clustered_total['Ordens'] == 1) | (df_clustered_total['PrecSum'] > 10)]
df_slice = df_cluster_hora.copy()
#df_slice = df_clustered_total[(df_clustered_total['Cluster'].isin([0]))]
#df_slice.loc[df_slice['Cluster'] == 0, 'Ordens'] = 0

df_slice.loc[(df_slice['LocalMax'] == 1) & (df_slice['PrecSum'] <= 10), 'LocalMax'] = 0

#df_slice.loc[(df_slice['Ordens'] == 1) & ~((df_clustered_total[[c for c in df_clustered_total.columns if 'Hora_' in c]] <= 20).sum(axis = 1) < 24), 'Ordens'] = 0
#df_slice = df_slice[df_slice['Local'] == 4]

In [96]:
df_slice.groupby('LocalMax').count()

Data_Hora   Local  UmidadeRelativa  PressaoAtmosferica  \
LocalMax                                                           
0.0          358978  358978           358978              358978   
1.0            6952    6952             6952                6952   

          TemperaturaDoAr  TemperaturaInterna  PontoDeOrvalho  RadiacaoSolar  \
LocalMax                                                                       
0.0                358978              358978          358978         358978   
1.0                  6952                6952            6952           6952   

          DirecaoDoVento  VelocidadeDoVento  Precipitacao    Data  Prec24h  \
LocalMax                                                                     
0.0               358978             358978        358978  358978   358978   
1.0                 6952               6952          6952    6952     6952   

          PrecSum    Hora     Mes  Minuto  
LocalMax                                   
0.0        358978  358978  358978  358978  
1.0          6952    6952    6952    6952

In [97]:
df_slice.shape

(365930, 18)

In [84]:
for l in range(6):
    if l != 0:
        df_train = df_slice[df_slice['Local'] == l]
    else:
        df_train = df_slice.copy()
        
    print(f'----- LOCAL {l} -----')

    # Testar prever cluster

    xgb = xgboost.XGBClassifier()

    cols_rem = ['LocalMax', 'Cluster', 'Data', 'Hora', 'Data_Hora', 'Ordens', 'Minuto'] + [c for c in df_train.columns if 'Hora_' in c]
    #cols_rem = cols_rem + ['DirecaoDoVento', 'VelocidadeDoVento']
    #cols_rem = cols_rem + ['TemperaturaInterna', 'PontoDeOrvalho']

    x = df_train[[c for c in df_train.columns if c not in cols_rem]]
    if l == 0:
        print(x.columns)
    #x = x.drop(columns = 'Cluster')
    y = df_train['LocalMax']

    x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state = 378, stratify=y)

    # concatenate our training data back together
    X = pd.concat([x_treino, y_treino], axis=1)

    # separate minority and majority classes
    not_ordem = X[X['LocalMax']==0].copy()
    ordem = X[X['LocalMax']==1].copy()

    # upsample minority
    ordem_upsampled = resample(ordem,
                            replace=True, # sample with replacement
                            n_samples=len(not_ordem), # match number in majority class
                            random_state=378) # reproducible results

    # combine majority and upsampled minority
    upsampled = pd.concat([not_ordem, ordem_upsampled])

    x_treino = upsampled[[c for c in df_slice.columns if c not in cols_rem]]
    y_treino = upsampled['LocalMax']

    display(y_treino.value_counts())

    #xgb.fit(x_treino, y_treino, eval_set = [(x_treino, y_treino), (x_teste, y_teste)], eval_metric=f1_score)
    param = {'max_depth':50, 'eta':1, 'objective':'binary:logistic', 'min_child_weight': 1, 'lambda': 1, 'alpha': 0, 'gamma': 0}

    df_train = xgboost.DMatrix(data=x_treino, label=y_treino)
    df_test = xgboost.DMatrix(data=x_teste, label=y_teste)

    bst = xgboost.train(param, df_train, 2, feval=f1_score)
    y_teste_pred = bst.predict(xgboost.DMatrix(data=x_teste, label=y_teste))
    y_teste_pred = [1 if i>0.5 else 0 for i in y_teste_pred]
    y_treino_pred = bst.predict(xgboost.DMatrix(data=x_treino, label=y_treino))
    y_treino_pred = [1 if i>0.5 else 0 for i in y_treino_pred]

    print(f"Treino: {accuracy_score(y_treino, y_treino_pred)}")
    print(f"Teste: {accuracy_score(y_teste, y_teste_pred)}")
    print(f"Precisão: {precision_score(y_teste, y_teste_pred)}")
    print(f"Recall: {recall_score(y_teste, y_teste_pred)}")
    print(f"F1: {f1_score(y_teste, y_teste_pred)}")
    display(confusion_matrix(y_teste, y_teste_pred, normalize='true'))
    display(confusion_matrix(y_teste, y_teste_pred,))

----- LOCAL 0 -----
Index(['Local', 'UmidadeRelativa', 'PressaoAtmosferica', 'TemperaturaDoAr',
       'TemperaturaInterna', 'PontoDeOrvalho', 'RadiacaoSolar',
       'DirecaoDoVento', 'VelocidadeDoVento', 'Precipitacao', 'PrecSum',
       'Mes'],
      dtype='object')


1.0    251866
0.0    251866
Name: LocalMax, dtype: int64

Treino: 0.9954003319225302
Teste: 0.9758697018555461
Precisão: 0.36009648518263265
Recall: 0.5688622754491018
F1: 0.4410213125131885


array([[0.98279632, 0.01720368],
       [0.43113772, 0.56886228]])

array([[106085,   1857],
       [   792,   1045]], dtype=int64)

----- LOCAL 1 -----


1.0    50277
0.0    50277
Name: LocalMax, dtype: int64

Treino: 0.9961314318674543
Teste: 0.9768628165421752
Precisão: 0.41776315789473684
Recall: 0.6225490196078431
F1: 0.5


array([[0.98357156, 0.01642844],
       [0.37745098, 0.62254902]])

array([[21194,   354],
       [  154,   254]], dtype=int64)

----- LOCAL 2 -----


1.0    50419
0.0    50419
Name: LocalMax, dtype: int64

Treino: 0.9958944048870465
Teste: 0.9803242849335033
Precisão: 0.42015209125475284
Recall: 0.6350574712643678
F1: 0.5057208237986269


array([[0.98588486, 0.01411514],
       [0.36494253, 0.63505747]])

array([[21303,   305],
       [  127,   221]], dtype=int64)

----- LOCAL 3 -----


1.0    50389
0.0    50389
Name: LocalMax, dtype: int64

Treino: 0.9955942765286074
Teste: 0.9778648205501913
Precisão: 0.3827392120075047
Recall: 0.5650969529085873
F1: 0.45637583892617456


array([[0.98476499, 0.01523501],
       [0.43490305, 0.56509695]])

array([[21266,   329],
       [  157,   204]], dtype=int64)

----- LOCAL 4 -----


1.0    50303
0.0    50303
Name: LocalMax, dtype: int64

Treino: 0.9951295151382621
Teste: 0.9729914374202951
Precisão: 0.34782608695652173
Recall: 0.5642317380352645
F1: 0.4303554274735831


array([[0.98051858, 0.01948142],
       [0.43576826, 0.56423174]])

array([[21139,   420],
       [  173,   224]], dtype=int64)

----- LOCAL 5 -----


1.0    50477
0.0    50477
Name: LocalMax, dtype: int64

Treino: 0.9961368544089387
Teste: 0.9800965567498634
Precisão: 0.3903846153846154
Recall: 0.628482972136223
F1: 0.4816132858837485


array([[0.98534646, 0.01465354],
       [0.37151703, 0.62848297]])

array([[21316,   317],
       [  120,   203]], dtype=int64)

In [98]:
test_cases = [
    [],
    ['DirecaoDoVento', 'VelocidadeDoVento'],
    ['DirecaoDoVento', 'VelocidadeDoVento', 'TemperaturaInterna'],
    ['DirecaoDoVento', 'VelocidadeDoVento', 'TemperaturaInterna', 'PontoDeOrvalho'],
    ['DirecaoDoVento', 'VelocidadeDoVento', 'TemperaturaInterna', 'PontoDeOrvalho', 'UmidadeRelativa'],
    ['DirecaoDoVento', 'VelocidadeDoVento', 'TemperaturaInterna', 'PontoDeOrvalho', 'UmidadeRelativa', 'PressaoAtmosferica'],
    ['DirecaoDoVento', 'VelocidadeDoVento', 'TemperaturaInterna', 'PontoDeOrvalho', 'UmidadeRelativa', 'PressaoAtmosferica', 'RadiacaoSolar'],
    ['DirecaoDoVento', 'VelocidadeDoVento', 'TemperaturaInterna', 'PontoDeOrvalho', 'UmidadeRelativa', 'PressaoAtmosferica', 'RadiacaoSolar', 'TemperaturaDoAr'],
    ['DirecaoDoVento', 'VelocidadeDoVento', 'TemperaturaInterna', 'PontoDeOrvalho', 'UmidadeRelativa', 'PressaoAtmosferica', 'RadiacaoSolar', 'TemperaturaDoAr', 'Local'],
    ['DirecaoDoVento', 'VelocidadeDoVento', 'TemperaturaInterna', 'PontoDeOrvalho', 'UmidadeRelativa', 'PressaoAtmosferica', 'RadiacaoSolar', 'TemperaturaDoAr', 'PrecSum'],
    ['DirecaoDoVento', 'VelocidadeDoVento', 'TemperaturaInterna', 'PontoDeOrvalho', 'UmidadeRelativa', 'PressaoAtmosferica', 'RadiacaoSolar', 'TemperaturaDoAr', 'Precipitacao']
]

df_training_result = pd.DataFrame(columns = ['Removed_Cols', 'Remaining_Cols', 'Local', 'Train_Acc', 'Test_Acc', 'Precision', 'Recall', 'F1', 'Ver_Pos'])

for case in test_cases:
    for l in range(6):
        if l != 0:
            df_train = df_slice[df_slice['Local'] == l]
        else:
            df_train = df_slice.copy()

        print(f'----- LOCAL {l} -----')

        # Testar prever cluster

        xgb = xgboost.XGBClassifier()

        cols_rem = ['LocalMax', 'Cluster', 'Data', 'Hora', 'Data_Hora', 'Ordens', 'Minuto'] + [c for c in df_train.columns if 'Hora_' in c]
        cols_rem = cols_rem + case
        #cols_rem = cols_rem + ['TemperaturaInterna', 'PontoDeOrvalho']

        x = df_train[[c for c in df_train.columns if c not in cols_rem]]
        if l == 0:
            print(x.columns)
        #x = x.drop(columns = 'Cluster')
        y = df_train['LocalMax']

        x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state = 378, stratify=y)

        # concatenate our training data back together
        X = pd.concat([x_treino, y_treino], axis=1)

        # separate minority and majority classes
        not_ordem = X[X['LocalMax']==0].copy()
        ordem = X[X['LocalMax']==1].copy()

        # upsample minority
        ordem_upsampled = resample(ordem,
                                replace=True, # sample with replacement
                                n_samples=len(not_ordem), # match number in majority class
                                random_state=378) # reproducible results

        # combine majority and upsampled minority
        upsampled = pd.concat([not_ordem, ordem_upsampled])

        x_treino = upsampled[[c for c in df_slice.columns if c not in cols_rem]]
        y_treino = upsampled['LocalMax']

        display(y_treino.value_counts())

        #xgb.fit(x_treino, y_treino, eval_set = [(x_treino, y_treino), (x_teste, y_teste)], eval_metric=f1_score)
        param = {'max_depth':50, 'eta':1, 'objective':'binary:logistic', 'min_child_weight': 1, 'lambda': 1, 'alpha': 0, 'gamma': 0}

        df_train = xgboost.DMatrix(data=x_treino, label=y_treino)
        df_test = xgboost.DMatrix(data=x_teste, label=y_teste)

        bst = xgboost.train(param, df_train, 2, feval=f1_score)
        y_teste_pred = bst.predict(xgboost.DMatrix(data=x_teste, label=y_teste))
        y_teste_pred = [1 if i>0.5 else 0 for i in y_teste_pred]
        y_treino_pred = bst.predict(xgboost.DMatrix(data=x_treino, label=y_treino))
        y_treino_pred = [1 if i>0.5 else 0 for i in y_treino_pred]

        print(f"Treino: {accuracy_score(y_treino, y_treino_pred)}")
        print(f"Teste: {accuracy_score(y_teste, y_teste_pred)}")
        print(f"Precisão: {precision_score(y_teste, y_teste_pred)}")
        print(f"Recall: {recall_score(y_teste, y_teste_pred)}")
        print(f"F1: {f1_score(y_teste, y_teste_pred)}")
        display(confusion_matrix(y_teste, y_teste_pred, normalize='true'))
        display(confusion_matrix(y_teste, y_teste_pred,))
        
        df_training_result = df_training_result.append({
            'Removed_Cols': case,
            'Remaining_Cols': list(x.columns),
            'Local': l,
            'Train_Acc': accuracy_score(y_treino, y_treino_pred),
            'Test_Acc': accuracy_score(y_teste, y_teste_pred),
            'Precision': precision_score(y_teste, y_teste_pred),
            'Recall': recall_score(y_teste, y_teste_pred),
            'F1': f1_score(y_teste, y_teste_pred),
            'Ver_Pos': confusion_matrix(y_teste, y_teste_pred, normalize='true')[1,1]
        }, ignore_index=True)

----- LOCAL 0 -----
Index(['Local', 'UmidadeRelativa', 'PressaoAtmosferica', 'TemperaturaDoAr',
       'TemperaturaInterna', 'PontoDeOrvalho', 'RadiacaoSolar',
       'DirecaoDoVento', 'VelocidadeDoVento', 'Precipitacao', 'Prec24h',
       'Mes'],
      dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.994436595897089
Teste: 0.9719345229962014
Precisão: 0.35028588624736684
Recall: 0.5580057526366251
F1: 0.43039378813089296


array([[0.97995227, 0.02004773],
       [0.44199425, 0.55800575]])

array([[105534,   2159],
       [   922,   1164]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.99489419414029
Teste: 0.9706230643104391
Precisão: 0.36795252225519287
Recall: 0.5310492505353319
F1: 0.4347063978965819


array([[0.9801759 , 0.0198241 ],
       [0.46895075, 0.53104925]])

array([[21063,   426],
       [  219,   248]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.9948019162343212
Teste: 0.971716159591911
Precisão: 0.31942215088282505
Recall: 0.5025252525252525
F1: 0.3905789990186457


array([[0.98033395, 0.01966605],
       [0.49747475, 0.50252525]])

array([[21136,   424],
       [  197,   199]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.995207890079736
Teste: 0.970167607943159
Precisão: 0.3173913043478261
Recall: 0.543424317617866
F1: 0.40073193046660566


array([[0.97814689, 0.02185311],
       [0.45657568, 0.54342432]])

array([[21082,   471],
       [  184,   219]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.9948529558170559
Teste: 0.970167607943159
Precisão: 0.3187702265372168
Recall: 0.45707656612529
F1: 0.37559580552907534


array([[0.98044135, 0.01955865],
       [0.54292343, 0.45707657]])

array([[21104,   421],
       [  234,   197]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.9955389078769573
Teste: 0.9756786299872472
Precisão: 0.37435008665511266
Recall: 0.5552699228791774
F1: 0.4472049689440994


array([[0.98326146, 0.01673854],
       [0.44473008, 0.55526992]])

array([[21206,   361],
       [  173,   216]], dtype=int64)

----- LOCAL 0 -----
Index(['Local', 'UmidadeRelativa', 'PressaoAtmosferica', 'TemperaturaDoAr',
       'TemperaturaInterna', 'PontoDeOrvalho', 'RadiacaoSolar', 'Precipitacao',
       'Prec24h', 'Mes'],
      dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.9946833276956444
Teste: 0.9740296413703896
Precisão: 0.3815422731495819
Recall: 0.5906040268456376
F1: 0.4635936030103481


array([[0.98145655, 0.01854345],
       [0.40939597, 0.59060403]])

array([[105696,   1997],
       [   854,   1232]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.994265940684896
Teste: 0.9709418837675351
Precisão: 0.37733142037302725
Recall: 0.563169164882227
F1: 0.4518900343642612


array([[0.97980362, 0.02019638],
       [0.43683084, 0.56316916]])

array([[21055,   434],
       [  204,   263]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.9952591090703083
Teste: 0.9750865367097832
Precisão: 0.37225042301184436
Recall: 0.5555555555555556
F1: 0.4457953394123607


array([[0.98279221, 0.01720779],
       [0.44444444, 0.55555556]])

array([[21189,   371],
       [  176,   220]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.9952973693106122
Teste: 0.9742667152486791
Precisão: 0.3722397476340694
Recall: 0.5856079404466501
F1: 0.45515911282545807


array([[0.98153389, 0.01846611],
       [0.41439206, 0.58560794]])

array([[21155,   398],
       [  167,   236]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.9948828226111542
Teste: 0.9724448897795591
Precisão: 0.36363636363636365
Recall: 0.5382830626450116
F1: 0.4340505144995323


array([[0.98113821, 0.01886179],
       [0.46171694, 0.53828306]])

array([[21119,   406],
       [  199,   232]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.9954892297909547
Teste: 0.9750409910730552
Precisão: 0.3681592039800995
Recall: 0.570694087403599
F1: 0.44758064516129026


array([[0.98233412, 0.01766588],
       [0.42930591, 0.57069409]])

array([[21186,   381],
       [  167,   222]], dtype=int64)

----- LOCAL 0 -----
Index(['Local', 'UmidadeRelativa', 'PressaoAtmosferica', 'TemperaturaDoAr',
       'PontoDeOrvalho', 'RadiacaoSolar', 'Precipitacao', 'Prec24h', 'Mes'],
      dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.9943828720377261
Teste: 0.9733919966478106
Precisão: 0.3714197720973206
Recall: 0.5781399808245445
F1: 0.45227826739171195


array([[0.98104798, 0.01895202],
       [0.42186002, 0.57813998]])

array([[105652,   2041],
       [   880,   1206]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.9945252198887093
Teste: 0.971397340134815
Precisão: 0.3810930576070901
Recall: 0.5524625267665952
F1: 0.451048951048951


array([[0.98050165, 0.01949835],
       [0.44753747, 0.55246253]])

array([[21070,   419],
       [  209,   258]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.9947025264873676
Teste: 0.9747221716159592
Precisão: 0.3728
Recall: 0.5883838383838383
F1: 0.45641527913809987


array([[0.98181818, 0.01818182],
       [0.41161616, 0.58838384]])

array([[21168,   392],
       [  163,   233]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.9954465013620727
Teste: 0.9743578065221352
Precisão: 0.37577639751552794
Recall: 0.6004962779156328
F1: 0.46227316141356256


array([[0.9813483 , 0.0186517 ],
       [0.39950372, 0.60049628]])

array([[21151,   402],
       [  161,   242]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.995510025287219
Teste: 0.9735379850610312
Precisão: 0.37664473684210525
Recall: 0.531322505800464
F1: 0.44080846968238685


array([[0.98239257, 0.01760743],
       [0.46867749, 0.53132251]])

array([[21146,   379],
       [  202,   229]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.99522096812654
Teste: 0.9751320823465112
Precisão: 0.3748006379585327
Recall: 0.6041131105398457
F1: 0.4625984251968504


array([[0.98182408, 0.01817592],
       [0.39588689, 0.60411311]])

array([[21175,   392],
       [  154,   235]], dtype=int64)

----- LOCAL 0 -----
Index(['Local', 'UmidadeRelativa', 'PressaoAtmosferica', 'TemperaturaDoAr',
       'RadiacaoSolar', 'Precipitacao', 'Prec24h', 'Mes'],
      dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.9942794038641384
Teste: 0.9734375426994234
Precisão: 0.3770734597156398
Recall: 0.6102588686481304
F1: 0.4661296228487733


array([[0.98047227, 0.01952773],
       [0.38974113, 0.61025887]])

array([[105590,   2103],
       [   813,   1273]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.9941163565288498
Teste: 0.969529969028967
Precisão: 0.3557142857142857
Recall: 0.5331905781584583
F1: 0.4267352185089975


array([[0.97901252, 0.02098748],
       [0.46680942, 0.53319058]])

array([[21038,   451],
       [  218,   249]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.9955672172858648
Teste: 0.9764529058116233
Precisão: 0.3929203539823009
Recall: 0.5606060606060606
F1: 0.4620187304890739


array([[0.98409091, 0.01590909],
       [0.43939394, 0.56060606]])

array([[21217,   343],
       [  174,   222]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.995237716490028
Teste: 0.9753142648934232
Precisão: 0.3877221324717286
Recall: 0.5955334987593052
F1: 0.46966731898238745


array([[0.98241544, 0.01758456],
       [0.4044665 , 0.5955335 ]])

array([[21174,   379],
       [  163,   240]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.9950421121796786
Teste: 0.9736746219712151
Precisão: 0.38639876352395675
Recall: 0.580046403712297
F1: 0.463821892393321


array([[0.98155633, 0.01844367],
       [0.4199536 , 0.5800464 ]])

array([[21128,   397],
       [  181,   250]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.9949527064621254
Teste: 0.9743122608854072
Precisão: 0.3655913978494624
Recall: 0.6118251928020566
F1: 0.45769230769230773


array([[0.98085037, 0.01914963],
       [0.38817481, 0.61182519]])

array([[21154,   413],
       [  151,   238]], dtype=int64)

----- LOCAL 0 -----
Index(['Local', 'PressaoAtmosferica', 'TemperaturaDoAr', 'RadiacaoSolar',
       'Precipitacao', 'Prec24h', 'Mes'],
      dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.993561095966731
Teste: 0.9726177137703933
Precisão: 0.36990950226244346
Recall: 0.6270373921380633
F1: 0.46531483457844186


array([[0.97931156, 0.02068844],
       [0.37296261, 0.62703739]])

array([[105465,   2228],
       [   778,   1308]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.9939568000957338
Teste: 0.9710329750409911
Precisão: 0.3791130185979971
Recall: 0.5674518201284796
F1: 0.45454545454545453


array([[0.97980362, 0.02019638],
       [0.43254818, 0.56745182]])

array([[21055,   434],
       [  202,   265]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.9943745403224203
Teste: 0.9755419930770632
Precisão: 0.3872
Recall: 0.6111111111111112
F1: 0.4740450538687561


array([[0.98223562, 0.01776438],
       [0.38888889, 0.61111111]])

array([[21177,   383],
       [  154,   242]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.9948002624724106
Teste: 0.9719894334122791
Precisão: 0.34411764705882353
Recall: 0.5806451612903226
F1: 0.4321329639889197


array([[0.97930683, 0.02069317],
       [0.41935484, 0.58064516]])

array([[21107,   446],
       [  169,   234]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.9943551759154172
Teste: 0.9706230643104391
Precisão: 0.3492957746478873
Recall: 0.5754060324825986
F1: 0.4347063978965819


array([[0.97853659, 0.02146341],
       [0.42459397, 0.57540603]])

array([[21063,   462],
       [  183,   248]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.9948036722041174
Teste: 0.9747677172526872
Precisão: 0.3667205169628433
Recall: 0.583547557840617
F1: 0.4503968253968254


array([[0.98182408, 0.01817592],
       [0.41645244, 0.58354756]])

array([[21175,   392],
       [  162,   227]], dtype=int64)

----- LOCAL 0 -----
Index(['Local', 'TemperaturaDoAr', 'RadiacaoSolar', 'Precipitacao', 'Prec24h',
       'Mes'],
      dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.9911574507033846
Teste: 0.9693839441058855
Precisão: 0.3353989155693261
Recall: 0.6227229146692234
F1: 0.43597919113945294


array([[0.97609873, 0.02390127],
       [0.37727709, 0.62272291]])

array([[105119,   2574],
       [   787,   1299]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.9903268912423463
Teste: 0.9633813080706868
Precisão: 0.3033838973162194
Recall: 0.556745182012848
F1: 0.39274924471299094


array([[0.97221834, 0.02778166],
       [0.44325482, 0.55674518]])

array([[20892,   597],
       [  207,   260]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.9912636412427694
Teste: 0.971716159591911
Precisão: 0.33766233766233766
Recall: 0.5909090909090909
F1: 0.4297520661157025


array([[0.97871058, 0.02128942],
       [0.40909091, 0.59090909]])

array([[21101,   459],
       [  162,   234]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.9920661748623014
Teste: 0.9694388777555111
Precisão: 0.31842818428184283
Recall: 0.5831265508684863
F1: 0.4119193689745837


array([[0.97666218, 0.02333782],
       [0.41687345, 0.58312655]])

array([[21050,   503],
       [  168,   235]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.9918463652111582
Teste: 0.9698032428493351
Precisão: 0.3428184281842818
Recall: 0.5870069605568445
F1: 0.4328485885372113


array([[0.97746806, 0.02253194],
       [0.41299304, 0.58700696]])

array([[21040,   485],
       [  178,   253]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.9922700898179795
Teste: 0.967844780470031
Precisão: 0.2928104575163399
Recall: 0.5758354755784062
F1: 0.38821490467937614


array([[0.97491538, 0.02508462],
       [0.42416452, 0.57583548]])

array([[21026,   541],
       [  165,   224]], dtype=int64)

----- LOCAL 0 -----
Index(['Local', 'TemperaturaDoAr', 'Precipitacao', 'Prec24h', 'Mes'], dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.9883319736554111
Teste: 0.9643556600078339
Precisão: 0.29668373024705097
Recall: 0.6390220517737296
F1: 0.40522875816993464


array([[0.97065733, 0.02934267],
       [0.36097795, 0.63902205]])

array([[104533,   3160],
       [   753,   1333]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.9874349308921199
Teste: 0.9604208416833667
Precisão: 0.2977867203219316
Recall: 0.6338329764453962
F1: 0.405201916495551


array([[0.96751827, 0.03248173],
       [0.36616702, 0.63383298]])

array([[20791,   698],
       [  171,   296]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.9908660822549545
Teste: 0.9700309710329751
Precisão: 0.3239247311827957
Recall: 0.6085858585858586
F1: 0.42280701754385963


array([[0.97666976, 0.02333024],
       [0.39141414, 0.60858586]])

array([[21057,   503],
       [  155,   241]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.9884571792169573
Teste: 0.9633813080706868
Precisão: 0.2759776536312849
Recall: 0.6129032258064516
F1: 0.38058551617873654


array([[0.96993458, 0.03006542],
       [0.38709677, 0.61290323]])

array([[20905,   648],
       [  156,   247]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.9891782649383748
Teste: 0.9650664966296228
Precisão: 0.3023529411764706
Recall: 0.5962877030162413
F1: 0.4012490241998439


array([[0.97245064, 0.02754936],
       [0.4037123 , 0.5962877 ]])

array([[20932,   593],
       [  174,   257]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.9909188458787059
Teste: 0.9653853160867188
Precisão: 0.2701363073110285
Recall: 0.5604113110539846
F1: 0.36454849498327757


array([[0.97268976, 0.02731024],
       [0.43958869, 0.56041131]])

array([[20978,   589],
       [  171,   218]], dtype=int64)

----- LOCAL 0 -----
Index(['Local', 'Precipitacao', 'Prec24h', 'Mes'], dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.9562807171140338
Teste: 0.953042020787218
Precisão: 0.23836317135549873
Recall: 0.6701821668264621
F1: 0.3516538800150925


array([[0.95852098, 0.04147902],
       [0.32981783, 0.67018217]])

array([[103226,   4467],
       [   688,   1398]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.9546560561638645
Teste: 0.9436145017307342
Precisão: 0.21840759678597516
Recall: 0.6402569593147751
F1: 0.32570806100217864


array([[0.95020708, 0.04979292],
       [0.35974304, 0.64025696]])

array([[20419,  1070],
       [  168,   299]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.96659510604886
Teste: 0.9565950081982146
Precisão: 0.24284395198522624
Recall: 0.6641414141414141
F1: 0.35564570655848543


array([[0.9619666 , 0.0380334 ],
       [0.33585859, 0.66414141]])

array([[20740,   820],
       [  133,   263]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.953172535841403
Teste: 0.9511750774275824
Precisão: 0.21914357682619648
Recall: 0.6476426799007444
F1: 0.32747804265997493


array([[0.95685055, 0.04314945],
       [0.35235732, 0.64764268]])

array([[20623,   930],
       [  142,   261]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.9628058857495569
Teste: 0.9542721807250866
Precisão: 0.23930846223839855
Recall: 0.6102088167053364
F1: 0.3437908496732026


array([[0.96116144, 0.03883856],
       [0.38979118, 0.61020882]])

array([[20689,   836],
       [  168,   263]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.951156505842143
Teste: 0.9525414465294225
Precisão: 0.2163336229365769
Recall: 0.6401028277634961
F1: 0.32337662337662343


array([[0.95817684, 0.04182316],
       [0.35989717, 0.64010283]])

array([[20665,   902],
       [  140,   249]], dtype=int64)

----- LOCAL 0 -----
Index(['Precipitacao', 'Prec24h', 'Mes'], dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.9379489424358796
Teste: 0.9400249592362838
Precisão: 0.1884178442781934
Recall: 0.6519654841802492
F1: 0.292347377472055


array([[0.94560464, 0.05439536],
       [0.34803452, 0.65196548]])

array([[101835,   5858],
       [   726,   1360]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.9546560561638645
Teste: 0.9436145017307342
Precisão: 0.21840759678597516
Recall: 0.6402569593147751
F1: 0.32570806100217864


array([[0.95020708, 0.04979292],
       [0.35974304, 0.64025696]])

array([[20419,  1070],
       [  168,   299]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.96659510604886
Teste: 0.9565950081982146
Precisão: 0.24284395198522624
Recall: 0.6641414141414141
F1: 0.35564570655848543


array([[0.9619666 , 0.0380334 ],
       [0.33585859, 0.66414141]])

array([[20740,   820],
       [  133,   263]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.953172535841403
Teste: 0.9511750774275824
Precisão: 0.21914357682619648
Recall: 0.6476426799007444
F1: 0.32747804265997493


array([[0.95685055, 0.04314945],
       [0.35235732, 0.64764268]])

array([[20623,   930],
       [  142,   261]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.9628058857495569
Teste: 0.9542721807250866
Precisão: 0.23930846223839855
Recall: 0.6102088167053364
F1: 0.3437908496732026


array([[0.96116144, 0.03883856],
       [0.38979118, 0.61020882]])

array([[20689,   836],
       [  168,   263]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.951156505842143
Teste: 0.9525414465294225
Precisão: 0.2163336229365769
Recall: 0.6401028277634961
F1: 0.32337662337662343


array([[0.95817684, 0.04182316],
       [0.35989717, 0.64010283]])

array([[20665,   902],
       [  140,   249]], dtype=int64)

----- LOCAL 0 -----
Index(['Local', 'Precipitacao', 'Prec24h', 'Mes'], dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.9562807171140338
Teste: 0.953042020787218
Precisão: 0.23836317135549873
Recall: 0.6701821668264621
F1: 0.3516538800150925


array([[0.95852098, 0.04147902],
       [0.32981783, 0.67018217]])

array([[103226,   4467],
       [   688,   1398]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.9546560561638645
Teste: 0.9436145017307342
Precisão: 0.21840759678597516
Recall: 0.6402569593147751
F1: 0.32570806100217864


array([[0.95020708, 0.04979292],
       [0.35974304, 0.64025696]])

array([[20419,  1070],
       [  168,   299]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.96659510604886
Teste: 0.9565950081982146
Precisão: 0.24284395198522624
Recall: 0.6641414141414141
F1: 0.35564570655848543


array([[0.9619666 , 0.0380334 ],
       [0.33585859, 0.66414141]])

array([[20740,   820],
       [  133,   263]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.953172535841403
Teste: 0.9511750774275824
Precisão: 0.21914357682619648
Recall: 0.6476426799007444
F1: 0.32747804265997493


array([[0.95685055, 0.04314945],
       [0.35235732, 0.64764268]])

array([[20623,   930],
       [  142,   261]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.9628058857495569
Teste: 0.9542721807250866
Precisão: 0.23930846223839855
Recall: 0.6102088167053364
F1: 0.3437908496732026


array([[0.96116144, 0.03883856],
       [0.38979118, 0.61020882]])

array([[20689,   836],
       [  168,   263]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.951156505842143
Teste: 0.9525414465294225
Precisão: 0.2163336229365769
Recall: 0.6401028277634961
F1: 0.32337662337662343


array([[0.95817684, 0.04182316],
       [0.35989717, 0.64010283]])

array([[20665,   902],
       [  140,   249]], dtype=int64)

----- LOCAL 0 -----
Index(['Local', 'Prec24h', 'Mes'], dtype='object')


1.0    251285
0.0    251285
Name: LocalMax, dtype: int64

Treino: 0.9477167359770778
Teste: 0.9376110185008062
Precisão: 0.18643844634628046
Recall: 0.6788111217641419
F1: 0.2925317632475984


array([[0.94262394, 0.05737606],
       [0.32118888, 0.67881112]])

array([[101514,   6179],
       [   670,   1416]], dtype=int64)

----- LOCAL 1 -----


1.0    50139
0.0    50139
Name: LocalMax, dtype: int64

Treino: 0.9456311454157442
Teste: 0.9258517034068137
Precisão: 0.17184850197851895
Recall: 0.6509635974304069
F1: 0.27191413237924866


array([[0.93182559, 0.06817441],
       [0.3490364 , 0.6509636 ]])

array([[20024,  1465],
       [  163,   304]], dtype=int64)

----- LOCAL 2 -----


1.0    50307
0.0    50307
Name: LocalMax, dtype: int64

Treino: 0.9590613632297692
Teste: 0.9444798688285663
Precisão: 0.196309963099631
Recall: 0.6717171717171717
F1: 0.3038263849229012


array([[0.9494898 , 0.0505102 ],
       [0.32828283, 0.67171717]])

array([[20471,  1089],
       [  130,   266]], dtype=int64)

----- LOCAL 3 -----


1.0    50291
0.0    50291
Name: LocalMax, dtype: int64

Treino: 0.9452387107037045
Teste: 0.9406540353434141
Precisão: 0.18354430379746836
Recall: 0.6476426799007444
F1: 0.286027397260274


array([[0.94613279, 0.05386721],
       [0.35235732, 0.64764268]])

array([[20392,  1161],
       [  142,   261]], dtype=int64)

----- LOCAL 4 -----


1.0    50223
0.0    50223
Name: LocalMax, dtype: int64

Treino: 0.9553192760289111
Teste: 0.9468026963016943
Precisão: 0.21500386697602475
Recall: 0.6450116009280742
F1: 0.3225058004640371


array([[0.95284553, 0.04715447],
       [0.3549884 , 0.6450116 ]])

array([[20510,  1015],
       [  153,   278]], dtype=int64)

----- LOCAL 5 -----


1.0    50324
0.0    50324
Name: LocalMax, dtype: int64

Treino: 0.9409526269771878
Teste: 0.938057934049918
Precisão: 0.17262306136210384
Recall: 0.6580976863753213
F1: 0.2735042735042735


array([[0.94310753, 0.05689247],
       [0.34190231, 0.65809769]])

array([[20340,  1227],
       [  133,   256]], dtype=int64)

In [99]:
# pd.DataFrame(
#     columns = ['Case', 'Local', 'Train_Acc', 'Test_Acc', 'Precision', 'Recall', 'F1', 'Ver_Pos']
# ).append({
#     'Case': case,
#     'Local': l,
#     'Train_Acc': accuracy_score(y_treino, y_treino_pred),
#     'Test_Acc': accuracy_score(y_teste, y_teste_pred),
#     'Precision': precision_score(y_teste, y_teste_pred),
#     'Recall': recall_score(y_teste, y_teste_pred),
#     'F1': f1_score(y_teste, y_teste_pred),
#     'Ver_Pos': confusion_matrix(y_teste, y_teste_pred, normalize='true')[1,1]
# }, ignore_index=True)
#{'Camilopolis': 1, 'Erasmo': 2, 'Paraiso': 3, 'RM': 4, 'Vitoria': 5}
display(df_training_result.tail(30))
#df_training_result.to_csv('training_test.csv', sep=';')

Removed_Cols  \
36  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
37  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
38  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
39  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
40  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
41  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
42  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
43  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
44  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
45  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
46  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
47  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
48  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
49  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
50  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
51  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
52  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
53  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
54  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
55  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
56  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
57  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
58  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
59  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
60  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
61  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
62  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
63  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
64  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   
65  [DirecaoDoVento, VelocidadeDoVento, Temperatur...   

                                       Remaining_Cols Local  Train_Acc  \
36  [Local, TemperaturaDoAr, Precipitacao, Prec24h...     0   0.988332   
37  [Local, TemperaturaDoAr, Precipitacao, Prec24h...     1   0.987435   
38  [Local, TemperaturaDoAr, Precipitacao, Prec24h...     2   0.990866   
39  [Local, TemperaturaDoAr, Precipitacao, Prec24h...     3   0.988457   
40  [Local, TemperaturaDoAr, Precipitacao, Prec24h...     4   0.989178   
41  [Local, TemperaturaDoAr, Precipitacao, Prec24h...     5   0.990919   
42                [Local, Precipitacao, Prec24h, Mes]     0   0.956281   
43                [Local, Precipitacao, Prec24h, Mes]     1   0.954656   
44                [Local, Precipitacao, Prec24h, Mes]     2   0.966595   
45                [Local, Precipitacao, Prec24h, Mes]     3   0.953173   
46                [Local, Precipitacao, Prec24h, Mes]     4   0.962806   
47                [Local, Precipitacao, Prec24h, Mes]     5   0.951157   
48                       [Precipitacao, Prec24h, Mes]     0   0.937949   
49                       [Precipitacao, Prec24h, Mes]     1   0.954656   
50                       [Precipitacao, Prec24h, Mes]     2   0.966595   
51                       [Precipitacao, Prec24h, Mes]     3   0.953173   
52                       [Precipitacao, Prec24h, Mes]     4   0.962806   
53                       [Precipitacao, Prec24h, Mes]     5   0.951157   
54                [Local, Precipitacao, Prec24h, Mes]     0   0.956281   
55                [Local, Precipitacao, Prec24h, Mes]     1   0.954656   
56                [Local, Precipitacao, Prec24h, Mes]     2   0.966595   
57                [Local, Precipitacao, Prec24h, Mes]     3   0.953173   
58                [Local, Precipitacao, Prec24h, Mes]     4   0.962806   
59                [Local, Precipitacao, Prec24h, Mes]     5   0.951157   
60                              [Local, Prec24h, Mes]     0   0.947717   
61                              [Local, Prec24h, Mes]     1   0.945631   
62                              [Local, Prec24h, Mes]     2   0.959061   
63                              [Local, Prec24h, Mes]     3   0.945239   
64                              [Local, Prec24h, Mes]     4   0.955319   
65                              [Local, Prec24h, Mes]

In [20]:
df_slice.drop(columns=['Data', 'Hora'])#.to_csv('dados_treinamento_15min.csv')
# [['Local', 'UmidadeRelativa', 'PressaoAtmosferica', 'TemperaturaDoAr', 'TemperaturaInterna',
#           'PontoDeOrvalho', 'RadiacaoSolar', 'DirecaoDoVento', 'VelocidadeDoVento', 'Precipitacao'
#           'PrecSum', 'LocalMax']]

Data_Hora  Local  UmidadeRelativa  PressaoAtmosferica  \
0       2011-01-01 00:00:00      1             84.8               920.6   
1       2011-01-01 00:15:00      1             84.1               920.3   
2       2011-01-01 00:30:00      1             83.9               920.2   
3       2011-01-01 00:45:00      1             83.5               919.9   
4       2011-01-01 01:00:00      1             84.0               919.9   
...                     ...    ...              ...                 ...   
1463565 2019-06-30 22:45:00      5             32.6               925.9   
1463566 2019-06-30 23:00:00      5             34.2               925.9   
1463567 2019-06-30 23:15:00      5             35.2               925.9   
1463568 2019-06-30 23:30:00      5             36.1               925.8   
1463569 2019-06-30 23:45:00      5             38.4               925.8   

         TemperaturaDoAr  TemperaturaInterna  PontoDeOrvalho  RadiacaoSolar  \
0                   20.2                22.8            17.5            0.0   
1                   20.1                22.8            17.4            0.0   
2                   20.1                22.9            17.2            0.0   
3                   20.2                22.9            17.3            0.0   
4                   20.1                22.8            17.3            0.0   
...                  ...                 ...             ...            ...   
1463565             21.7                27.9             5.2            0.0   
1463566             21.3                27.9             5.5            0.0   
1463567             21.0                27.7             5.6            0.0   
1463568             20.8                27.6             5.9            0.0   
1463569             20.3                27.5             6.3            0.0   

         DirecaoDoVento  VelocidadeDoVento  Precipitacao  LocalMax  PrecSum  
0                 137.0                1.5           0.0       0.0      0.6  
1                  76.0                1.9           0.0       0.0      0.6  
2                  92.0                2.9           0.0       0.0      0.6  
3                 133.0                1.4           0.0       0.0      0.6  
4                 151.0                1.8           0.0       0.0      0.6  
...                 ...                ...           ...       ...      ...  
1463565             0.0                0.0           0.0       0.0      0.0  
1463566             0.0                0.0           0.0       0.0      0.0  
1463567             0.0                0.0           0.0       0.0      0.0  
1463568             0.0                0.0           0.0       0.0      0.0  
1463569             0.0                0.0           0.0       0.0      0.0  

[1463570 rows x 13 columns]